mapping:
  'Christopher Boelter <christopher@boelter.eu>':
    - 'Christopher Bölter <christopher@boelter.eu>'
    - 'Christopher Bölter <github@boelter.eu>'
    - 'cboelter <christopher@boelter.eu>'
